package com;

import com.milsoft.help.HelpFile;
import com.milsoft.help.pdf.PdfBookmarkExtractor;
import com.milsoft.help.pdf.chromium.ChromiumPdfHelpManager;
import com.milsoft.help.pdf.javafx.FxWebViewHelpManager;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.io.File;
import java.util.Comparator;
import java.util.Map;

public class MilsoftHelp {
    private JPanel panel;
    private JRadioButton fxWebViewRadioButton;
    private JRadioButton chromiumRadioButton;
    private JTextField pdfFileField;
    private JButton chooseButton;
    private JPanel helpChooser;
    private JButton openBookmarkButton;
    private JComboBox bookmarkCombo;
    private JTextField pageNoField;
    private JButton openPageButton;

    private Process process;
    private HelpFile helpFile;
    private FxWebViewHelpManager fxWebViewHelpManager;
    private ChromiumPdfHelpManager chromiumPdfHelpManager;
    private JFileChooser chooser;


    public MilsoftHelp() {
        fxWebViewHelpManager = new FxWebViewHelpManager(null);
        chromiumPdfHelpManager = new ChromiumPdfHelpManager(new File("C:\\Users\\iciftci\\Downloads\\chrome-win\\mil-chrome.exe"));

        chooseButton.addActionListener(e -> {
            chooser = new JFileChooser(pdfFileField.getText());
            chooser.setFileFilter(new FileNameExtensionFilter("PDF (*.pdf)", "pdf"));
            int ret = chooser.showOpenDialog(null);
            File selectedFile = chooser.getSelectedFile();
            if (selectedFile != null) {
                pdfFileField.setText(selectedFile.toPath().toAbsolutePath().toString());
                helpFile = new HelpFile(selectedFile);
                PdfBookmarkExtractor extractor = new PdfBookmarkExtractor(selectedFile);
                Map<String, Integer> bookmarkMap = extractor.extract();
                Object[] bookmarks = bookmarkMap.entrySet().stream()
                        .sorted(Comparator.comparingInt(Map.Entry::getValue))
                        .map(entry -> entry.getKey())
                        .toArray();

                bookmarkCombo.setModel(new DefaultComboBoxModel(bookmarks));

                fxWebViewHelpManager.register(helpFile);
                chromiumPdfHelpManager.register(helpFile);
            }


        });
        openBookmarkButton.addActionListener(e -> {
            String pdfFile = pdfFileField.getText();
            String bookmark = (String) bookmarkCombo.getSelectedItem();


            if (fxWebViewRadioButton.isSelected()) {
                fxWebViewHelpManager.open(helpFile.getFileKey(), helpFile.getBookmarkToPageMap().get(bookmarkCombo.getSelectedItem()));
            } else {
                chromiumPdfHelpManager.open(helpFile.getFileKey(), helpFile.getBookmarkToPageMap().get(bookmarkCombo.getSelectedItem()));
            }
        });

        openPageButton.addActionListener(e -> {
            String pdfFile = pdfFileField.getText();
            Integer page = 1;
            try {
                page = Integer.parseInt(pageNoField.getText());
            } catch (Exception ex) {

            }


            if (fxWebViewRadioButton.isSelected()) {
                fxWebViewHelpManager.open(helpFile.getFileKey(), page);
            } else {
                chromiumPdfHelpManager.open(helpFile.getFileKey(), page);
            }
        });
    }

    public JPanel getHelpChooser() {
        return helpChooser;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        helpChooser = new JPanel();
        helpChooser.setLayout(new GridBagLayout());
        helpChooser.setEnabled(true);
        pdfFileField = new JTextField();
        pdfFileField.setText("C:\\Users\\iciftci\\Desktop\\modem-tools\\docs\\The Windows Serial Port Programming Handbook.pdf");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 5, 5);
        helpChooser.add(pdfFileField, gbc);
        chooseButton = new JButton();
        chooseButton.setText("Choose");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 5, 5);
        helpChooser.add(chooseButton, gbc);
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 5, 5, 5);
        helpChooser.add(panel, gbc);
        fxWebViewRadioButton = new JRadioButton();
        fxWebViewRadioButton.setSelected(true);
        fxWebViewRadioButton.setText("Fx-WebView");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 0, 0);
        panel.add(fxWebViewRadioButton, gbc);
        chromiumRadioButton = new JRadioButton();
        chromiumRadioButton.setText("Chromium");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 0, 0);
        panel.add(chromiumRadioButton, gbc);
        openBookmarkButton = new JButton();
        openBookmarkButton.setText("Open");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 5, 5);
        helpChooser.add(openBookmarkButton, gbc);
        bookmarkCombo = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 5, 5);
        helpChooser.add(bookmarkCombo, gbc);
        pageNoField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 5, 5);
        helpChooser.add(pageNoField, gbc);
        openPageButton = new JButton();
        openPageButton.setText("Open");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 5, 5);
        helpChooser.add(openPageButton, gbc);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(fxWebViewRadioButton);
        buttonGroup.add(chromiumRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return helpChooser;
    }
}
